version: '2'
services:
  go:
    build: .
    image: golang
    volumes:
      - .:/go/src/github.com/fajarpnugroho/pengine
    working_dir: /go/src/github.com/fajarpnugroho/pengine
    command: go run main.go
    links:
      - postgres:db
    ports:
      - "8080"
    environment:
      - POSTGRES_1_PORT_5432_TCP_ADDR=172.18.0.2
      - POSTGRES_1_PORT_5432_TCP_PORT=5432
  postgres:
    image: postgres_panggilin
    ports:
      - "5432"
  proxy:
    image: nginx_panggilin
    ports:
        - "80:80" # host:container
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        # connect host's ./nginx.conf with container's nginx.conf
        # :ro == read only perms in container
    links:
        - go:go # [other container]:[alias in this container]
          # creates environment variables in proxy container
          # with ip and port info for go container
          # also creates entries in /etc/hosts with ip info
